[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Tambahkan ini untuk memastikan redirects bekerja
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
