[build]
  command = "npm run build"
  publish = "_site"  # Sesuaikan dengan output di .eleventy.js

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
